### ISSUE TITLE
Todo Command

### ISSUE THREAD

**Issue by Homosanians** [Homosanians/OWRP#7]
/todo Эй, мужик!*помахав рукой человеку в далеке.
> Эй, мужик!, — сказал игрок, помахав рукой человеку в далеке.

```
  todo:
    description: Todo command
    permission: owrp.todo
    usage: /<command>
```
